# Server config
server:
  ## Should be included to show message, if not error message will be empty
  error:
    include-message: always
    include-binding-errors: always

app:
  eureka:
    host: localhost
    port: 8761
    user: blabla-eureka-user
    pass: blabla-eureka-password
  kafka:
    broker:
      host: your_kafka_host
      port: 9092
    api:
      key: your_kafka_username
      secret: your_kafka_password

spring:
  kafka:
    bootstrap-servers: ${app.kafka.broker.host}:${app.kafka.broker.port}
    properties:
      security.protocol: SASL_SSL
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='${app.kafka.api.key}'   password='${app.kafka.api.secret}';
        mechanism: PLAIN
      ssl:
        endpoint.identification.algorithm: https
    producer:
      properties:
        spring.json.add.type.headers: false
    consumer:
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
      # NOTE: Add all events here
      topic:
        createdPosts: created-posts
        joinedRoomMember: joined-room-member
        leavedRoomMember: leaved-room-member

  cloud:
    # As Spring Cloud Ribbon is in maintenance mode.
    # It is recommended switching to BlockingLoadBalancerClient instead.
    loadbalancer.ribbon.enabled: false

  # TODO: Disable distributed tracing by default (with zipkin and sleuth)

# Service discovery
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.int}
    hostname: ${app.eureka.host}
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${app.eureka.user}:${app.eureka.pass}@${app.eureka.host}:${app.eureka.port}/eureka/
    healthcheck:
      enabled: true

# Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: ALWAYS

---
spring:
  config:
    activate:
      on-profile: prod

app:
  eureka:
    host: your_production_discovery_url
    user: blabla-eureka-user
    pass: blabla-eureka-password

eureka:
  instance:
    hostname: ${app.eureka.host}
    secure-port-enabled: true
    nonsecure-port-enabled: false
    non-secure-port: 80
    secure-port: 443
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${app.eureka.host}:443/eureka/