app:
  azure:
    storage:
      accountName: azure_storage_name
      accountKey: azure_storage_connection_string

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: prod